"use client"

import { useState } from "react"
import { KeyRound, X } from "lucide-react"
import { authClient } from "@/lib/auth-client"

export function AccountSettings() {
  const [open, setOpen] = useState(false); const [current, setCurrent] = useState(""); const [next, setNext] = useState(""); const [confirm, setConfirm] = useState(""); const [message, setMessage] = useState(""); const [saving, setSaving] = useState(false)
  async function submit(event: React.FormEvent) { event.preventDefault(); setMessage(""); if (next.length < 8) return setMessage("Your new password must be at least 8 characters."); if (next !== confirm) return setMessage("The new passwords do not match."); setSaving(true); const { error } = await authClient.changePassword({ currentPassword: current, newPassword: next, revokeOtherSessions: false }); setMessage(error ? "Could not change your password. Check your current password." : "Password changed successfully."); if (!error) { setCurrent(""); setNext(""); setConfirm("") } setSaving(false) }
  return <><button type="button" onClick={() => { setOpen(true); setMessage("") }} className="inline-flex items-center gap-2 rounded-full border border-border bg-card/50 px-4 py-2 text-sm font-medium text-muted-foreground backdrop-blur-md transition-colors hover:border-primary/40 hover:text-foreground"><KeyRound className="size-4" /> Change password</button>{open ? <div className="fixed inset-0 z-50 flex items-center justify-center bg-background/80 p-4 backdrop-blur-sm" role="dialog" aria-modal="true" aria-labelledby="password-title"><form onSubmit={submit} className="flex w-full max-w-md flex-col gap-4 rounded-2xl border border-border bg-card p-6 shadow-2xl"><div className="flex items-center justify-between"><div><h2 id="password-title" className="font-display text-xl font-semibold">Change password</h2><p className="text-sm text-muted-foreground">Keep your account secure.</p></div><button type="button" onClick={() => setOpen(false)} aria-label="Close" className="rounded-lg p-2 text-muted-foreground hover:text-foreground"><X className="size-5" /></button></div>{[["Current password", current, setCurrent], ["New password", next, setNext], ["Confirm new password", confirm, setConfirm]].map(([label, value, setter]) => <label key={label as string} className="flex flex-col gap-1.5 text-sm font-medium">{label as string}<input required type="password" value={value as string} onChange={e => (setter as (v: string) => void)(e.target.value)} className="rounded-lg border border-input bg-secondary px-3 py-2 outline-none focus:ring-2 focus:ring-ring" /></label>)}{message ? <p className="text-sm text-muted-foreground">{message}</p> : null}<button disabled={saving} className="rounded-lg bg-primary px-4 py-2.5 font-medium text-primary-foreground disabled:opacity-60">{saving ? "Saving..." : "Update password"}</button></form></div> : null}</>
}
