"use client"

import { useState } from "react"
import { X, Plus } from "lucide-react"
import type { Game, GameStatus } from "@/lib/types"

export function ManualGameDialog({ onAdd }: { onAdd: (game: Game, status: GameStatus) => Promise<void> }) {
  const [open, setOpen] = useState(false); const [name, setName] = useState(""); const [image, setImage] = useState(""); const [tags, setTags] = useState(""); const [status, setStatus] = useState<GameStatus>("not_played"); const [saving, setSaving] = useState(false); const [error, setError] = useState("")
  async function submit(event: React.FormEvent) { event.preventDefault(); if (!name.trim()) return setError("Enter a game name."); setSaving(true); setError(""); let hash = 0; for (const c of name.trim()) hash = (hash * 31 + c.charCodeAt(0)) | 0; const id = hash === 0 ? -1 : -Math.abs(hash); const game: Game = { id, slug: name.trim().toLowerCase().replace(/\s+/g, "-"), name: name.trim(), released: null, background_image: image.trim() || null, metacritic: null, rating: 0, ratings_count: 0, genres: [], tags: tags.split(",").map((tag, i) => tag.trim()).filter(Boolean).map((tag, i) => ({ id: id - i - 1, name: tag, slug: tag.toLowerCase().replace(/\s+/g, "-") })), parent_platforms: [], isManual: true }; try { await onAdd(game, status); setOpen(false); setName(""); setImage(""); setTags("") } catch (e) { setError(e instanceof Error ? e.message : "Could not add game") } finally { setSaving(false) } }
  return <>
    <button type="button" onClick={() => setOpen(true)} className="inline-flex items-center gap-2 rounded-full border border-primary/40 bg-primary/10 px-4 py-2 text-sm font-medium text-primary transition-colors hover:bg-primary/20"><Plus className="size-4" /> Add game manually</button>
    {open ? <div className="fixed inset-0 z-50 flex items-center justify-center bg-background/80 p-4 backdrop-blur-sm" role="dialog" aria-modal="true" aria-labelledby="manual-game-title"><form onSubmit={submit} className="flex w-full max-w-md flex-col gap-4 rounded-2xl border border-border bg-card p-6 shadow-2xl"><div className="flex items-center justify-between"><div><h2 id="manual-game-title" className="font-display text-xl font-semibold">Add a game manually</h2><p className="text-sm text-muted-foreground">For anything you could not find in search.</p></div><button type="button" onClick={() => setOpen(false)} aria-label="Close" className="rounded-lg p-2 text-muted-foreground hover:text-foreground"><X className="size-5" /></button></div><label className="flex flex-col gap-1.5 text-sm font-medium">Name<input required maxLength={120} value={name} onChange={e => setName(e.target.value)} className="rounded-lg border border-input bg-secondary px-3 py-2 outline-none focus:ring-2 focus:ring-ring" /></label><label className="flex flex-col gap-1.5 text-sm font-medium">Image URL <span className="text-xs font-normal text-muted-foreground">Optional</span><input type="url" maxLength={2000} value={image} onChange={e => setImage(e.target.value)} className="rounded-lg border border-input bg-secondary px-3 py-2 outline-none focus:ring-2 focus:ring-ring" /></label><label className="flex flex-col gap-1.5 text-sm font-medium">Tags <span className="text-xs font-normal text-muted-foreground">Comma-separated, e.g. horror, RPG</span><input value={tags} onChange={e => setTags(e.target.value)} className="rounded-lg border border-input bg-secondary px-3 py-2 outline-none focus:ring-2 focus:ring-ring" /></label><label className="flex flex-col gap-1.5 text-sm font-medium">Status<select value={status} onChange={e => setStatus(e.target.value as GameStatus)} className="rounded-lg border border-input bg-secondary px-3 py-2 outline-none focus:ring-2 focus:ring-ring"><option value="playing">Playing</option><option value="played">Played</option><option value="not_played">Not played</option></select></label>{error ? <p className="text-sm text-destructive">{error}</p> : null}<button disabled={saving} className="rounded-lg bg-primary px-4 py-2.5 font-medium text-primary-foreground disabled:opacity-60">{saving ? "Adding..." : "Add to stack"}</button></form></div> : null}
  </>
}
