// A curated dictionary of well-known game titles / franchises used to expand
// short or partial queries (e.g. "assa" -> "Assassin's Creed") before hitting
// RAWG. This makes autocomplete-style prefixes resolve to real franchises
// instead of relying on RAWG's index matching very short strings.
export const POPULAR_GAMES: string[] = [
  "Assassin's Creed",
  "Assassin's Creed Valhalla",
  "Assassin's Creed Odyssey",
  "Assassin's Creed Origins",
  "Assassin's Creed Mirage",
  "Assassin's Creed Shadows",
  "The Legend of Zelda",
  "The Legend of Zelda: Breath of the Wild",
  "The Legend of Zelda: Tears of the Kingdom",
  "The Witcher 3: Wild Hunt",
  "The Witcher",
  "Cyberpunk 2077",
  "Grand Theft Auto V",
  "Grand Theft Auto San Andreas",
  "Red Dead Redemption 2",
  "Red Dead Redemption",
  "Elden Ring",
  "Dark Souls III",
  "Dark Souls",
  "Bloodborne",
  "Sekiro: Shadows Die Twice",
  "Resident Evil",
  "Resident Evil 4",
  "Resident Evil Village",
  "Resident Evil 2",
  "Silent Hill 2",
  "Silent Hill",
  "Outlast",
  "Amnesia: The Dark Descent",
  "Dead Space",
  "Dead by Daylight",
  "Phasmophobia",
  "The Evil Within",
  "Alien: Isolation",
  "Left 4 Dead 2",
  "Layers of Fear",
  "God of War",
  "God of War Ragnarök",
  "Horizon Zero Dawn",
  "Horizon Forbidden West",
  "The Last of Us",
  "The Last of Us Part II",
  "Uncharted 4: A Thief's End",
  "Ghost of Tsushima",
  "Marvel's Spider-Man",
  "Marvel's Spider-Man 2",
  "Death Stranding",
  "Detroit: Become Human",
  "Bloodstained: Ritual of the Night",
  "Hollow Knight",
  "Hades",
  "Celeste",
  "Stardew Valley",
  "Terraria",
  "Minecraft",
  "Roblox",
  "Fortnite",
  "Apex Legends",
  "Call of Duty",
  "Call of Duty: Modern Warfare",
  "Call of Duty: Warzone",
  "Battlefield 1",
  "Counter-Strike 2",
  "Counter-Strike: Global Offensive",
  "Valorant",
  "Overwatch 2",
  "Rainbow Six Siege",
  "Destiny 2",
  "Halo Infinite",
  "Halo: The Master Chief Collection",
  "Doom Eternal",
  "Doom",
  "Wolfenstein: The New Order",
  "Far Cry 5",
  "Far Cry 6",
  "Far Cry 3",
  "Borderlands 3",
  "Borderlands 2",
  "The Elder Scrolls V: Skyrim",
  "The Elder Scrolls Online",
  "Fallout 4",
  "Fallout: New Vegas",
  "Fallout 76",
  "Starfield",
  "Mass Effect Legendary Edition",
  "Mass Effect 2",
  "Dragon Age: Inquisition",
  "Dragon Age: The Veilguard",
  "Baldur's Gate 3",
  "Divinity: Original Sin 2",
  "Diablo IV",
  "Diablo III",
  "Path of Exile",
  "World of Warcraft",
  "Final Fantasy VII Remake",
  "Final Fantasy XVI",
  "Final Fantasy XIV",
  "Persona 5 Royal",
  "Persona 3 Reload",
  "Nier: Automata",
  "Monster Hunter: World",
  "Monster Hunter Rise",
  "Monster Hunter Wilds",
  "Sea of Thieves",
  "No Man's Sky",
  "Subnautica",
  "Valheim",
  "Rust",
  "Palworld",
  "Grounded",
  "It Takes Two",
  "A Way Out",
  "Cuphead",
  "Ori and the Blind Forest",
  "Ori and the Will of the Wisps",
  "Super Mario Odyssey",
  "Super Mario Bros. Wonder",
  "Mario Kart 8 Deluxe",
  "Animal Crossing: New Horizons",
  "Splatoon 3",
  "Metroid Dread",
  "Kirby and the Forgotten Land",
  "Pokemon Scarlet",
  "Pokemon Violet",
  "Pokemon Legends: Arceus",
  "Xenoblade Chronicles 3",
  "Fire Emblem: Three Houses",
  "Sonic Frontiers",
  "Street Fighter 6",
  "Tekken 8",
  "Mortal Kombat 1",
  "Mortal Kombat 11",
  "Guilty Gear Strive",
  "FIFA 23",
  "EA Sports FC 24",
  "NBA 2K24",
  "Rocket League",
  "Gran Turismo 7",
  "Forza Horizon 5",
  "Forza Horizon 4",
  "Need for Speed Heat",
  "The Sims 4",
  "Cities: Skylines",
  "Civilization VI",
  "Age of Empires IV",
  "Total War: Warhammer III",
  "XCOM 2",
  "Frostpunk",
  "RimWorld",
  "Factorio",
  "Satisfactory",
  "Portal 2",
  "Portal",
  "Half-Life 2",
  "Half-Life: Alyx",
  "BioShock Infinite",
  "BioShock",
  "Dishonored 2",
  "Prey",
  "Control",
  "Alan Wake 2",
  "Alan Wake",
  "Returnal",
  "Deathloop",
  "Disco Elysium",
  "Cult of the Lamb",
  "Vampire Survivors",
  "Slay the Spire",
  "Balatro",
  "Lethal Company",
  "Helldivers 2",
  "Baldur's Gate",
  "Kingdom Come: Deliverance",
  "Kingdom Come: Deliverance II",
  "Metal Gear Solid V: The Phantom Pain",
  "Metal Gear Solid",
  "Devil May Cry 5",
  "Bayonetta 3",
  "Nioh 2",
  "Lies of P",
  "Black Myth: Wukong",
  "Stellar Blade",
  "Hi-Fi Rush",
  "Tunic",
  "Pentiment",
  "Sifu",
  "GTA IV",
  "Watch Dogs 2",
  "Watch Dogs: Legion",
  "Just Cause 4",
  "Tomb Raider",
  "Shadow of the Tomb Raider",
  "Rise of the Tomb Raider",
]
